<section class="col-md-12">
    <div class="col-md-3">
    <?php echo $this->render('layout/app/menu'); ?>
    </div>
    <div class="col-md-9">
        <form method="post" action='<?php echo $this->url('backend-team', array('action'=>'index')); ?>'>
            <textarea class="ckeditor" name="content"><?php echo $this->content ;?></textarea>
            <input type='hidden' name='idPage' value='<?php echo $this->idPage; ?>'/>
            <input type='hidden' name="action" value="index"/>
            <p></p>
            <button type="submit" class="btn btn-wog"><?php echo $this->translate('Enregistrer'); ?></button>
        </form>
    </div>
</section>

<?php echo $this->headScript()
        ->appendFile($this->basePath('js/plugin/ckeditor/ckeditor.js'))
        ->appendFile($this->basePath('js/backend.js'));
?>