<?php
$recaptcha = new \Zend\ReCaptcha\ReCaptcha($this->publicKey, $this->privateKey, null,array('lang'=>'fr'));
?>
<section class="col-md-12">
    <div class="col-md-3"></div>
    <form class="form-horizontal col-md-6" method="post" action="<?php echo $this->url('contact', array('action' => 'getForm')); ?>">
        <div class="form-head">
            <h4><?php echo $this->translate('Laissez-nous un message'); ?></h4>
        </div>
        <div class="form-group">
            <label for="nameInput" class="control-label"><?php echo $this->translate('Nom'); ?></label>
            <input type="text" class="form-control" id="nameInput" name="name" placeholder="Name">
        </div>
        <div class="form-group">
            <label for="emailInput" class="control-label"><?php echo $this->translate('Adresse Email*'); ?></label>
            <input type="email" class="form-control" id="emailInput" name="email" placeholder="Email" required>
        </div>
        <div class="form-group">
            <label for="subjectInput" class="control-label"><?php echo $this->translate('Sujet*'); ?></label>
            <input type="text" class="form-control" id="subjectInput" name="subject" placeholder="Subject">
        </div>
        <div class="form-group">
            <label for="messageInput" class="control-label "><?php echo $this->translate('Comment pouvons-nous vous aider?*'); ?></label>
            <textarea class="form-control" id="messageInput" rows="5" name="message" required></textarea>
        </div>
        <div class="form-group">
            <?php echo $recaptcha->getHTML(); ?>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-wog btn-lg"><?php echo $this->translate('Envoyer'); ?></button>
        </div>
    </form>
    <div class="col-md-3"></div>
</section>