<form class="form-horizontal">
    <div class="form-head">
        <h4><?php echo $this->translate('Laissez-nous un message'); ?></h4>
    </div>
    <div class="form-group">
        <label for="nameInput" class="control-label"><?php echo $this->translate('Nom'); ?></label>
        <input type="text" class="form-control" id="nameInput" name="name" placeholder="Name">
    </div>
    <div class="form-group">
        <label for="emailInput" class="control-label"><?php echo $this->translate('Adresse Email*'); ?></label>
        <input type="email" class="form-control" id="emailInput" name="email" placeholder="Email" required>
    </div>
    <div class="form-group">
        <label for="subjectInput" class="control-label"><?php echo $this->translate('Sujet*'); ?></label>
        <input type="text" class="form-control" id="subjectInput" name="subject" placeholder="Subject">
    </div>
    <div class="form-group">
        <label for="messageInput" class="control-label "><?php echo $this->translate('Comment pouvons-nous vous aider?*'); ?></label>
        <textarea class="form-control" id="messageInput" rows="5" name="message" required></textarea>
    </div>
    <div class="form-group">
        <div class="g-recaptcha" data-sitekey="6Lff0wgUAAAAANlCdA-rkbJ93V33Z96r9IPYXpPB">
        </div>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-wog btn-lg"><?php echo $this->translate('Envoyer'); ?></button>
    </div>
</form>