<?php
$recaptcha = new \Zend\ReCaptcha\ReCaptcha($this->publicKey, $this->privateKey, null, array('lang' => 'fr'));
?>
<section>
    <div class="first-dark-part">
        <div>
            <div class="logo">
                <a href="<?php echo $this->url('home'); ?>">
                    <img style="width:200px;" src="<?php echo $this->basePath('img/Logo_WoGbis.png'); ?>" alt="logo WoG">
                </a>
            </div>
            <div class="col-md-3"></div>
            <form class="form-horizontal col-md-6" method="post" action="<?php echo $this->url('contact', array('action' => 'getForm')); ?>">
                <div class="form-head">
                    <h4><?php echo $this->translate('Laissez-nous un message'); ?></h4>
                </div>
                <div class="form-group">
                    <label for="nameInput" class="control-label"><?php echo $this->translate('Nom'); ?></label>
                    <input type="text" class="form-control" id="nameInput" name="name" placeholder="Name">
                </div>
                <div class="form-group">
                    <label for="emailInput" class="control-label"><?php echo $this->translate('Adresse Email*'); ?></label>
                    <input type="email" class="form-control" id="emailInput" name="email" placeholder="Email" required>
                </div>
                <div class="form-group">
                    <label for="subjectInput" class="control-label"><?php echo $this->translate('Sujet*'); ?></label>
                    <input type="text" class="form-control" id="subjectInput" name="subject" placeholder="Subject">
                </div>
                <div class="form-group">
                    <label for="messageInput" class="control-label "><?php echo $this->translate('Comment pouvons-nous vous aider?*'); ?></label>
                    <textarea class="form-control" id="messageInput" rows="5" name="message" required></textarea>
                </div>
                <div class="form-group">
                    <?php echo $recaptcha->getHTML(); ?>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-wog btn-lg"><?php echo $this->translate('Envoyer'); ?></button>
                </div>
            </form>
            <div class="col-md-3"></div>
        </div>
</section>
<section>
    <div class="light-part">
        <p><a href="https://worldofwarcraft.com/fr-fr/">Blizzard</a> | <a href="http://fr.wowhead.com">WoWHead</a> | <a href="http://www.wowprogress.com">WoWProgress</a></p>
        <strong>&copy; 2016 - <?php echo getdate()['year']; ?> by Wrath of God </strong> <i><?php echo $this->translate('Tous droits réservés.'); ?></i>
    </div>
</section>