<section>
    <div class="first-dark-part">
        <div class="content-container">
            <div class="logo">
                <a href="<?php echo $this->url('home'); ?>">
                    <img style="width:200px;" src="<?php echo $this->basePath('img/Logo_WoGbis.png'); ?>" alt="logo WoG">
                </a>
            </div>
            
            <div>
                <h1>Qui sommes-nous ? </h1>

                <p>
                    Les WoG existent depuis le 22 janvier 2008. Après avoir vécue quelques belles années de raid de Karazhan 
                    à la Descente de l’aile noir, la guilde a cessé d’exister. 
                    Oui la Pandarie aura eut raison de longues années de jeu commun, mais pas d’une amitié IRL qui s’est créée 
                    entre les membres fondateurs. Warlords of Draenor aura permis de réunir de nouveaux les pères 
                    fondateurs de cette guilde, d’abord sous une autre bannière, mais aujourd’hui de retour chez eux.<br><br> 
                    Moins investis qu'à l’époque pour des raisons familiale, Alax, Madryade, Olare, Redoot, 
                    Xéres sont de retour comme des Légendes de cette guilde. Quand à moi, Capi, j’ai repris cette guilde,
                    là où j’ai vécue mes plus belles années de jeu, et je souhaite redorer le blason de la 
                    famille Wrath of God ! <br><br>
                    A mes côtés, un ancien de la maison, le seigneur de Hurlevent, j’ai nommé Gadock. 
                    Ces quelques années dans une autre guilde m’auront aussi permis de me rapprocher de nouvelles personnes, 
                    toutes différentes, mais toutes investies pour un seul objectif, faire de cette guilde, un endroit où on 
                    se sent bien et où on peut profiter de ce que nous offre le jeu. Antarus, Failly, Kadyll, Jolarson, 
                    Lisys et bien sur Gadock, sont donc les personnes qui m’aident à faire avancer cette guilde.
                </p>
            </div>
            
        </div>
</section>
<section>
    <div class="light-part">
        <div class="content-container">
            <h1>Une nouvelle ère, un état d'esprit, un objectif</h1> 
            <p>
            <h4><i>Une nouvelle ère </i></h4> 
            Bien évidemment que les choses ont changé depuis BC, moins de temps de jeux, des familles, 
            d’autres envies, d’autres besoins. Aujourd’hui les WoG, existent pour le plaisir de ses membres, que tu sois un membre 
            actif pve, ou un joueur "casu" aimant partager une expérience de jeu, tu trouveras ton plaisir chez nous! 
            </p>
            <p>
            <h4><i>Un état d'esprit neuf </i></h4> 
            Nous souhaitions unir d'anciens membres, amis, connaissances afin de retrouver l'ambiance et 
            la cohésion qu'il existait autrefois. 
            </p>
            <p>
            <h4><i>Objectif et fonctionnement </i></h4>
            L’objectif de la guilde est de créer un climat positif, une guilde active, 
            qui permet à chacun de trouver son bonheur. 
            </p>
            <p>
            <h4><i>Le pve </i></h4>
            Il existe un roster pve qui a pour objectif minimum, de clean le contenue HM et de se mesurer 
            au contenue MM. En deux soirs par semaine, l’objectif a, à ce jour, toujours été atteind. Il existe aussi un petit 
            groupe (roster) qui raid une fois par semaine, en mode decouverte. Ainsi qu’un raid "reroll" deux vendredi soir par 
            mois, ouvert à tous.
            </p>

        </div>
    </div>
</section>
<section>
    <div class="dark-part">
        <p><a href="https://worldofwarcraft.com/fr-fr/">Blizzard</a> | <a href="http://fr.wowhead.com">WoWHead</a> | <a href="http://www.wowprogress.com">WoWProgress</a></p>
        <strong>&copy; 2016 - <?php echo getdate()['year']; ?> by Wrath of God </strong> <i><?php echo $this->translate('Tous droits réservés.'); ?></i>
    </div>
</section>