
<nav class="navbar navbar-default main-nav">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        
        <div class="collapse navbar-collapse" id="navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="<?php echo $this->url('home'); ?>"><?php echo $this->translate('Accueil'); ?></a></li>
                <li><a href="#"><?php echo $this->translate('Gallerie'); ?></a></li>
                <li><a href="#"><?php echo $this->translate('Team'); ?></a></li>
                <li><a href="forum.wrathofgod.fr"><?php echo $this->translate('Forum'); ?></a></li>
                <li><a href="<?php echo $this->url('contact');?>"><?php echo $this->translate('Contact'); ?></a></li>
            </ul>
        </div>
    </div>
</nav>
