<meta charset="utf-8">
<?php echo $this->headTitle($this->translate("Guilde Wrath of God | Sargeras – Garona – Ner'zhul"))->setSeparator(' - ')->setAutoEscape(false) ?>

<?php
echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
?>
<meta name="description" content="Site web de la guilde: Wrath Of God , Communauté de joueurs évoluant sur le jeu World of Warcraft. Guilde familiale se trouvant sur le groupement de serveurs Garona - Sargeras - Nerz'hul, avec pour ambition le clean du contenu HM." />
<meta name="Keyword" content="WoW, guilde, Garona, Sargeras, Ner'zhul, pve, HM" />

<!-- Le styles -->
<?php
echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->appendStylesheet($this->basePath('css/bootstrap.css'))
        ->appendStylesheet($this->basePath('css/style.css?vers=2.0.1'))
        ->appendStylesheet("https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css")
        ->appendStylesheet("https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css")
        ->appendStylesheet("https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css");

?>

<!-- Scripts -->
<?php
echo $this->headScript()
        ->appendFile($this->basePath('js/jquery.min.js'))
        ->appendFile($this->basePath('js/bootstrap.min.js'))
        ->appendFile($this->basePath('js/frontend.js'))
        ->appendFile("https://www.google.com/recaptcha/api.js")
;
?>