
<div class="nav-backend">

            <a href="<?php echo $this->url('backend-home'); ?>"class="btn btn-wog col-md-12"><?php echo $this->translate('News'); ?></a>
            <a href="<?php echo $this->url('backend-team'); ?>" class="btn btn-wog col-md-12"><?php echo $this->translate('Team'); ?></a>
            <a href="<?php echo $this->url('backend-gallery'); ?>" class="btn btn-wog col-md-12"><?php echo $this->translate('Gallery'); ?></a>

</div>

