<?php echo $this->plugin('doctype')->setDoctype(\Zend\View\Helper\Doctype::HTML5); ?>
<html lang="fr">
    <head>
        <?php echo $this->render('layout/app/head') ?>
        <script>
            (function (i, s, o, g, r, a, m) {
                i['GoogleAnalyticsObject'] = r;
                i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date();
                a = s.createElement(o),
                        m = s.getElementsByTagName(o)[0];
                a.async = 1;
                a.src = g;
                m.parentNode.insertBefore(a, m)
            })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

            ga('create', 'UA-72079314-3', 'auto');
            ga('send', 'pageview');

        </script>
    </head>
    <body>           
        <header>
            <div class="banner-shadow"></div>
            <?php echo $this->render('layout/app/header_menu') ?>
        </header>
        <!--                Container                -->
        <div id="bloc_page">
            <div class="fixed-background">
                <div class="col-md-3 welcome">
                    <p>Bienvenue sur le site de la guilde Wrath Of God</p>
                    <ul>
                        <li><a class="btn btn-info btn-nav" href="<?php echo $this->url('home'); ?>"><?php echo $this->translate('Accueil'); ?></a></li>
                        <li><a class="btn btn-info btn-nav" href="<?php echo $this->url('gallery'); ?>"><?php echo $this->translate('Gallerie'); ?></a></li>
                        <li><a class="btn btn-info btn-nav" href="<?php echo $this->url('team'); ?>"><?php echo $this->translate('Team'); ?></a></p>
                        <li><a class="btn btn-info btn-nav" href="http://forum.wrathofgod.fr"><?php echo $this->translate('Forum'); ?></a></li>
                        <li><a class="btn btn-info btn-nav" href="<?php echo $this->url('contact'); ?>"><?php echo $this->translate('Contact'); ?></a></li>
                    </ul>
                </div>
            </div>
            <?php echo $this->content; ?>
        </div>
        <!--               Footer                   -->

        <!--            Control sidebar             -->

        <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
