<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Backend\Controller\IndexController' => __DIR__ . '/src/Backend/Controller/IndexController.php',
    'Backend\Controller\PageTeamController' => __DIR__ . '/src/Backend/Controller/PageTeamController.php',
    'Backend\Controller\PageHomeController' => __DIR__ . '/src/Backend/Controller/PageHomeController.php',
    'Backend\Model\UsersTable'           => __DIR__ . '/src/Backend/Model/UsersTable.php',
    'Backend\Model\RolesTable'           => __DIR__ . '/src/Backend/Model/RolesTable.php',
    'Backend\Model\PagesTable'           => __DIR__ . '/src/Backend/Model/PagesTable.php',
    'Backend\Model\ContentPageTable'     => __DIR__ . '/src/Backend/Model/ContentPageTable.php',
    'Backend\Module'                     => __DIR__ . '/Module.php',
    
);
