<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Backend\Controller\IndexController' => __DIR__ . '/src/Backend/Controller/IndexController.php',
    'Backend\Module'                     => __DIR__ . '/Module.php',
    
);
